import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import DropDown from "../../../../../components/DropDown";

const Finall: NextPage = () => {
  const { opponentRace, raceName } = useRouter().query as {
    opponentRace: string;
    raceName: string;
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/sc2.png" />
      </Head>
      <main
        className="flex min-h-screen 
        flex-col items-center justify-center gap-4 bg-gradient-to-b 
        from-[#2e026d] to-[#15162c] text-white"
      >
        <h2 className="text-3xl text-white">
          {raceName} vs {opponentRace}
        </h2>

        <DropDown raceName={raceName} opponentRace={opponentRace} />
      </main>
    </>
  );
};

export default Finall;
