import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import RaceCard from "../../../../components/RaceCard";

const MatchUps: NextPage = () => {
  const { raceName } = useRouter().query as { raceName: string };

  return (
    <>
      <Head>
        <title>Races Match Ups</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/sc2.png" />
      </Head>
      <main
        className="flex min-h-screen 
        flex-col items-center justify-center gap-4 bg-gradient-to-b 
        from-[#2e026d] to-[#15162c] text-white"
      >
        <div className="flex flex-col gap-4 text-center">
          <h2>{raceName?.toUpperCase()}</h2>
          <p>vs.</p>
          <h2>Select Opponent's Race</h2>
        </div>

        <ul className="grid grid-cols-3 gap-10">
          <li>
            <RaceCard
              isOpponent
              raceHref={`/races/${raceName}/match-ups/terran`}
              raceName="terran"
              imgSrc={"/terran.jpg"}
            />
          </li>
          <li>
            <RaceCard
              isOpponent
              raceHref={`/races/${raceName}/match-ups/zerg`}
              raceName="zerg"
              imgSrc={"/zerg.jpg"}
            />
          </li>
          <li>
            <RaceCard
              isOpponent
              raceHref={`/races/${raceName}/match-ups/protoss`}
              raceName="protoss"
              imgSrc={"/protoss.jpg"}
            />
          </li>
        </ul>
      </main>
    </>
  );
};

export default MatchUps;
