import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Link from "next/link";

const BuildsPage: NextPage = () => {
  const builds = trpc.builds.getBuilds.useQuery();

  return (
    <>
      <Head>
        <title>Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen 
        flex-col items-center justify-center gap-4 bg-gradient-to-b 
        from-[#2e026d] to-[#15162c] text-white"
      >
        <h2>Builds</h2>

        <Link href="/">Home</Link>

        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Match Up</th>
              <th>Build</th>
            </tr>
          </thead>

          <tbody>
            {builds.data?.map((build: any) => (
              <tr key={build.id}>
                <td>{build.id}</td>
                <td>{build.matchUp}</td>
                <td>{build.build}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
};

export default BuildsPage;
